

import { useState, useEffect, useRef } from "react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Badge } from "@/components/ui/badge"
import { Spinner } from "@/components/ui/spinner"
import { Plane, ThumbsUp, Calendar, RefreshCw, Check } from "lucide-react"
import { Link, useNavigate, useParams } from "react-router-dom"
import { getVoteSummary, voteCandidatePlan, generateCandidates } from "@/api/candidates"
import { confirmPlans } from "@/api/plans"
import { getGroupDetail, getGroupMembers } from "@/api/group"
import { toast } from "react-toastify"

export default function PlansPage() {
  const navigate = useNavigate()
  const { id } = useParams()

  const [selectedPlan, setSelectedPlan] = useState("")
  const [candidatePlans, setCandidatePlans] = useState([])
  const [room, setRoom] = useState(null)
  const [members, setMembers] = useState([])
  const [userVote, setUserVote] = useState(null)
  const [isGenerating, setIsGenerating] = useState(false)
  const [loading, setLoading] = useState(false)
  const [isConfirming, setIsConfirming] = useState(false)
  const [error, setError] = useState(null)
  const autoGeneratedRef = useRef(false)

  // 그룹 정보 로드 (제목/마감일 표시용)
  useEffect(() => {
    const loadRoom = async () => {
      try {
        const [data, membersRes] = await Promise.all([
          getGroupDetail(id),
          getGroupMembers(id)
        ])
        setRoom(data)
        setMembers(membersRes?.Members || [])
      } catch (e) {
        // 그룹 정보 실패는 치명적이지 않으므로 조용히 무시
        console.warn('그룹 정보 로드 실패', e)
      }
    }
    if (id) loadRoom()
  }, [id])

  useEffect(() => {
    const load = async () => {
      try {
        setLoading(true)
        const summary = await getVoteSummary(id)
        setCandidatePlans(summary.candidatePlanList || [])
        // auto select first
        if (summary.candidatePlanList?.length) setSelectedPlan(summary.candidatePlanList[0].candidatePlanId)
        // find user vote
        const votedItem = summary.candidatePlanList.find(p => p.voted)
        setUserVote(votedItem ? votedItem.candidatePlanId : null)
      } catch (e) {
        setError(e.message || '후보 계획을 불러오지 못했습니다')
      } finally {
        setLoading(false)
        setIsGenerating(false)
      }
    }
    if (id) load()
  }, [id])

  // 후보가 없으면 자동 생성 시도 (쿼리 파라미터와 무관하게 동작)
  useEffect(() => {
    const autoGenerate = async () => {
      if (autoGeneratedRef.current) return
      if (loading) return
      if (candidatePlans.length > 0) return
      autoGeneratedRef.current = true
      try {
        setIsGenerating(true)
        await generateCandidates(id)
        // 생성 트리거 후, 투표 요약 API를 재조회하며 응답을 기다린다
        const summary = await getVoteSummary(id)
        const plans = summary?.candidatePlanList || []
        setCandidatePlans(plans)
        if (plans.length) setSelectedPlan(plans[0].candidatePlanId)
      } catch (e) {
        setError(e.message || '자동 생성 실패')
      } finally {
        setIsGenerating(false)
      }
    }
    autoGenerate()
  }, [loading, candidatePlans.length, id])

  const regenerate = async () => {
    try {
      setIsGenerating(true)
      await generateCandidates(id)
      const summary = await getVoteSummary(id)
      const plans = summary?.candidatePlanList || []
      setCandidatePlans(plans)
      if (plans.length) setSelectedPlan(plans[0].candidatePlanId)
    } catch (e) {
      toast.error(e.message || '재생성 실패')
    } finally {
      setIsGenerating(false)
    }
  }

  const handleVote = async (candidatePlanId) => {
    try {
      await voteCandidatePlan(id, candidatePlanId)
      const summary = await getVoteSummary(id)
      setCandidatePlans(summary.candidatePlanList || [])
      setUserVote(candidatePlanId)
    } catch (e) {
      toast.error(e.message || '투표 실패')
    }
  }

  const handleRegenerate = () => regenerate()

  const handleConfirm = async() => {
    try {
      // 방장만 확정 가능: 단순 프런트 가드
      const isLeader = members.find(m => m.userId === localStorage.getItem('userId'))?.role === 'LEADER'
      if (!isLeader) { toast.warn('방장만 확정할 수 있습니다'); return }
      // 사용자 확인 알림
      const ok = confirm('투표수에 따라 계획을 확정하시겠습니까?')
      if (!ok) return
      setIsConfirming(true)
      await confirmPlans(id)
      navigate(`/rooms/${id}/confirmed`)
    } catch (e) {
      toast.error(e.message || '계획 확정 중 오류가 발생했습니다')
    } finally {
      setIsConfirming(false)
    }
  }
  

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="border-b border-border">
        <div className="container mx-auto px-4 py-4 flex items-center justify-between">
          <Link to="/rooms" className="flex items-center gap-2">
            <Plane className="h-6 w-6 text-primary" />
            <span className="text-xl font-bold text-foreground">같이가자</span>
          </Link>
        </div>
      </header>

      <main className="container mx-auto px-4 py-8">
        <div className="max-w-5xl mx-auto">
          <div className="mb-6">
            <h1 className="text-3xl font-bold text-foreground mb-2">{room?.title || '여행 계획'}</h1>
            <p className="text-muted-foreground">두 가지 계획 중 마음에 드는 것에 투표해주세요</p>
          </div>

          {/* 후보 불러오는 중: 페이지는 유지하고 버튼/문구만 로딩 표시 */}
          <>
            {loading && (
              <div className="mb-4">
                <Spinner label="후보 일정을 불러오는 중..." size={28} />
              </div>
            )}
              {candidatePlans.length === 0 ? (
                <Card className="mb-6">
                  <CardHeader>
                    <CardTitle>후보 일정 없음</CardTitle>
                  </CardHeader>
                  <CardContent className="space-y-4">
                    <p className="text-sm text-muted-foreground">아직 생성된 후보 일정이 없습니다. 잠시만 기다려 주세요. 자동으로 후보 일정이 생성됩니다.</p>
                    {error && (
                      <p className="text-sm text-red-500">자동 생성 실패: {error}. 아래의 "계획 재생성" 버튼으로 다시 시도해 주세요.</p>
                    )}
                  </CardContent>
                </Card>
              ) : (
                <Tabs value={selectedPlan} onValueChange={setSelectedPlan} className="mb-6">
                  <TabsList className={`grid w-full h-auto p-1`} style={{ gridTemplateColumns: `repeat(${candidatePlans.length}, minmax(0,1fr))` }}>
                    {candidatePlans.map((c, idx) => (
                      <TabsTrigger
                        key={c.candidatePlanId}
                        value={c.candidatePlanId}
                        className="relative text-base font-semibold py-2 px-4 data-[state=active]:bg-primary data-[state=active]:text-primary-foreground"
                      >
                        계획 {idx + 1}
                        <Badge variant="secondary" className="ml-2 font-medium">
                          {c.votes}표
                        </Badge>
                      </TabsTrigger>
                    ))}
                  </TabsList>
                  {candidatePlans.map((c, idx) => (
                    <TabsContent key={c.candidatePlanId} value={c.candidatePlanId} className="space-y-6">
                      <Card>
                        <CardHeader>
                          <div className="flex flex-col sm:flex-row items-start justify-between gap-3">
                            <div>
                              <CardTitle>계획 {idx + 1}</CardTitle>
                              <p className="text-sm text-muted-foreground mt-2 whitespace-pre-line">{c.content}</p>
                            </div>
                            <Button
                              variant={userVote === c.candidatePlanId ? "default" : "outline"}
                              onClick={() => handleVote(c.candidatePlanId)}
                              className="w-full sm:w-auto"
                              disabled={!c.candidatePlanId || loading}
                            >
                              <ThumbsUp className="h-4 w-4 mr-2" />
                              {loading ? '불러오는 중...' : (userVote === c.candidatePlanId ? "투표됨" : "투표하기")}
                            </Button>
                          </div>
                        </CardHeader>
                        <CardContent className="space-y-6">
                          {/* 추가 설명 영역은 실제 데이터 스펙 확정 시 노출 예정 */}
                        </CardContent>
                      </Card>
                    </TabsContent>
                  ))}
                </Tabs>
              )}

              {/* Action Buttons */}
              <Card>
                <CardContent className="pt-6">
                  <div className="flex flex-col sm:flex-row gap-4 items-center justify-between">
                    {(() => {
                      if (!room?.rDeadline) return null
                      const today = new Date()
                      const deadline = new Date(room.rDeadline)
                      const daysRemaining = Math.ceil((deadline - today) / (1000 * 60 * 60 * 24))
                      return (
                        <div className="flex items-center gap-2 text-sm text-muted-foreground">
                          <Calendar className="h-4 w-4" />
                          <span>투표 마감까지 {daysRemaining}일 남음</span>
                        </div>
                      )
                    })()}
                    <div className="flex gap-3 w-full sm:w-auto">
                      <Button variant="outline" onClick={handleRegenerate} className="flex-1 sm:flex-none bg-transparent" disabled={isGenerating || loading || isConfirming}>
                        <RefreshCw className="h-4 w-4 mr-2" />{isGenerating ? '생성 중...' : (loading ? '불러오는 중...' : '계획 재생성')}
                      </Button>
                      <Button onClick={handleConfirm} className="flex-1 sm:flex-none" disabled={isConfirming || loading || isGenerating}>
                        <Check className="h-4 w-4 mr-2" />
                        {isConfirming ? '확정 처리 중...' : '계획 확정'}
                      </Button>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </>
        </div>
      </main>
    </div>
  )
}
