

import { useState, useEffect, useRef } from "react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Badge } from "@/components/ui/badge"
import { Plane, ThumbsUp, Calendar, RefreshCw, Check } from "lucide-react"
import { Link, useNavigate, useSearchParams, useParams } from "react-router-dom"
import { LoadingAnimation } from "@/components/loading-animation"
import { getVoteSummary, voteCandidatePlan, generateCandidates } from "@/api/candidates"

export default function PlansPage() {
  const navigate = useNavigate()
  const [searchParams] = useSearchParams()
  const { id } = useParams()
  const isInitialGeneration = searchParams.get("generating") === "true"

  const [selectedPlan, setSelectedPlan] = useState("")
  const [candidatePlans, setCandidatePlans] = useState([])
  const [userVote, setUserVote] = useState(null)
  const [isGenerating, setIsGenerating] = useState(isInitialGeneration)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState(null)
  const autoGeneratedRef = useRef(false)

  const daysRemaining = 3

  useEffect(() => {
    const load = async () => {
      try {
        setLoading(true)
        const summary = await getVoteSummary(id)
        setCandidatePlans(summary.candidatePlanList || [])
        // auto select first
        if (summary.candidatePlanList?.length) setSelectedPlan(summary.candidatePlanList[0].candidatePlanId)
        // find user vote
        const votedItem = summary.candidatePlanList.find(p => p.voted)
        setUserVote(votedItem ? votedItem.candidatePlanId : null)
      } catch (e) {
        setError(e.message || '후보 계획을 불러오지 못했습니다')
      } finally {
        setLoading(false)
        setIsGenerating(false)
      }
    }
    if (id) load()
  }, [id])

  // 최초 생성 플래그가 있고 아직 후보가 없으면 자동 생성 시도
  useEffect(() => {
    const autoGenerate = async () => {
      if (!isInitialGeneration) return
      if (autoGeneratedRef.current) return
      if (loading) return
      if (candidatePlans.length > 0) return
      autoGeneratedRef.current = true
      try {
        setIsGenerating(true)
        await generateCandidates(id)
        const summary = await getVoteSummary(id)
        setCandidatePlans(summary.candidatePlanList || [])
        if (summary.candidatePlanList?.length) setSelectedPlan(summary.candidatePlanList[0].candidatePlanId)
      } catch (e) {
        setError(e.message || '자동 생성 실패')
      } finally {
        setIsGenerating(false)
      }
    }
    autoGenerate()
  }, [isInitialGeneration, loading, candidatePlans.length, id])

  const regenerate = async () => {
    try {
      setIsGenerating(true)
      await generateCandidates(id)
      const summary = await getVoteSummary(id)
      setCandidatePlans(summary.candidatePlanList || [])
      if (summary.candidatePlanList?.length) setSelectedPlan(summary.candidatePlanList[0].candidatePlanId)
    } catch (e) {
      alert(e.message || '재생성 실패')
    } finally {
      setIsGenerating(false)
    }
  }

  const handleVote = async (candidatePlanId) => {
    try {
      await voteCandidatePlan(id, candidatePlanId)
      const summary = await getVoteSummary(id)
      setCandidatePlans(summary.candidatePlanList || [])
      setUserVote(candidatePlanId)
    } catch (e) {
      alert(e.message || '투표 실패')
    }
  }

  const handleRegenerate = () => regenerate()

  const handleConfirm = () => {
    if (!userVote) {
      alert('먼저 투표를 진행하세요')
      return
    }
    navigate(`/rooms/${id}/confirmed?plan=${userVote}`)
  }

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="border-b border-border">
        <div className="container mx-auto px-4 py-4 flex items-center justify-between">
          <Link to="/rooms" className="flex items-center gap-2">
            <Plane className="h-6 w-6 text-primary" />
            <span className="text-xl font-bold text-foreground">같이가자</span>
          </Link>
        </div>
      </header>

      <main className="container mx-auto px-4 py-8">
        <div className="max-w-5xl mx-auto">
          <div className="mb-6">
            <h1 className="text-3xl font-bold text-foreground mb-2">제주도 가족 여행 계획</h1>
            <p className="text-muted-foreground">두 가지 계획 중 마음에 드는 것에 투표해주세요</p>
          </div>

          {isGenerating ? (
            <LoadingAnimation />
          ) : (
            <>
              {candidatePlans.length === 0 ? (
                <Card className="mb-6">
                  <CardHeader>
                    <CardTitle>후보 일정 없음</CardTitle>
                  </CardHeader>
                  <CardContent className="space-y-4">
                    <p className="text-sm text-muted-foreground">아직 생성된 후보 일정이 없습니다. 먼저 재생성 버튼을 눌러 일정을 만들어 주세요.</p>
                    <Button variant="outline" onClick={handleRegenerate} className="w-full sm:w-auto">
                      <RefreshCw className="h-4 w-4 mr-2" />후보 일정 생성
                    </Button>
                  </CardContent>
                </Card>
              ) : (
                <Tabs value={selectedPlan} onValueChange={setSelectedPlan} className="mb-6">
                  <TabsList className={`grid w-full h-auto p-1`} style={{ gridTemplateColumns: `repeat(${candidatePlans.length}, minmax(0,1fr))` }}>
                    {candidatePlans.map((c, idx) => (
                      <TabsTrigger
                        key={c.candidatePlanId}
                        value={c.candidatePlanId}
                        className="relative text-base font-semibold py-2 px-4 data-[state=active]:bg-primary data-[state=active]:text-primary-foreground"
                      >
                        계획 {idx + 1}
                        <Badge variant="secondary" className="ml-2 font-medium">
                          {c.votes}표
                        </Badge>
                      </TabsTrigger>
                    ))}
                  </TabsList>
                  {candidatePlans.map((c, idx) => (
                    <TabsContent key={c.candidatePlanId} value={c.candidatePlanId} className="space-y-6">
                      <Card>
                        <CardHeader>
                          <div className="flex flex-col sm:flex-row items-start justify-between gap-3">
                            <div>
                              <CardTitle>계획 {idx + 1}</CardTitle>
                              <p className="text-sm text-muted-foreground mt-2">후보 일정 내용(모킹): {c.content}</p>
                            </div>
                            <Button
                              variant={userVote === c.candidatePlanId ? "default" : "outline"}
                              onClick={() => handleVote(c.candidatePlanId)}
                              className="w-full sm:w-auto"
                              disabled={!c.candidatePlanId}
                            >
                              <ThumbsUp className="h-4 w-4 mr-2" />
                              {userVote === c.candidatePlanId ? "투표됨" : "투표하기"}
                            </Button>
                          </div>
                        </CardHeader>
                        <CardContent className="space-y-6">
                          <Card className="bg-muted">
                            <CardHeader>
                              <CardTitle className="text-base">이 계획을 선택한 이유 (샘플)</CardTitle>
                            </CardHeader>
                            <CardContent>
                              <p className="text-sm text-muted-foreground leading-relaxed">의견 데이터 기반 개인화 사유는 추후 AI 연동 시 표시됩니다.</p>
                            </CardContent>
                          </Card>
                        </CardContent>
                      </Card>
                    </TabsContent>
                  ))}
                </Tabs>
              )}

              {/* Action Buttons */}
              <Card>
                <CardContent className="pt-6">
                  <div className="flex flex-col sm:flex-row gap-4 items-center justify-between">
                    <div className="flex items-center gap-2 text-sm text-muted-foreground">
                      <Calendar className="h-4 w-4" />
                      <span>투표 마감까지 {daysRemaining}일 남음</span>
                    </div>
                    <div className="flex gap-3 w-full sm:w-auto">
                      <Button variant="outline" onClick={handleRegenerate} className="flex-1 sm:flex-none bg-transparent" disabled={isGenerating}>
                        <RefreshCw className="h-4 w-4 mr-2" />{isGenerating ? '생성 중...' : '계획 재생성'}
                      </Button>
                      <Button onClick={handleConfirm} className="flex-1 sm:flex-none">
                        <Check className="h-4 w-4 mr-2" />
                        계획 확정
                      </Button>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </>
          )}
        </div>
      </main>
    </div>
  )
}
